[tools]
cocogitto = "6.4.0"   # renovate: github=cocogitto/cocogitto
gh = "2.83.1"    # renovate: github=cli/cli
marksman = "2026-02-08"   # renovate: github=artempyanykh/marksman
prek = "v0.3.4"   # renovate: github=j178/prek
